theme: jekyll-theme-minimal
title: ACSE
description: A description has to go here, but for now it is just this msg.
tagline: this is the tagline
logo: /Docs/Images/open-naja.jpg
show_downloads: true



author:
  name:  Inaki Lopez
  email: ignore@gmail.com
  social:
    twitter: ilodev
    github:  ilodev
  about: Hi, just a small bio about...
