theme: jekyll-theme-minimal
title: ACSE
description: The Awesome Cobra Script Extender (ACSE) is a tool used to expand scripting capabilities and add additional functionality to the games using Cobra engine.
tagline: this is the tagline
logo: /assets/images/open-naja.png
show_downloads: true



author:
  name:  Inaki Lopez
  email: ignore@gmail.com
  social:
    github:  ilodev
  about: Hi, just a small bio about...
